name: Build DLL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Install Visual Studio with C++ support
      uses: actions/runner-toolcache@v2
      with:
        toolName: Visual Studio
        toolVersion: latest

    - name: Compile C++ into DLL
      run: |
        cl /LD /Fe:output.dll source.cpp
      shell: cmd

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v3
      with:
        name: dll-artifact
        path: output.dll

