name: Build and Upload DLL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install dependencies (Visual Studio, CMake, etc.)
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      # Install CMake
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1

      # Configure the project with CMake
      - name: Configure with CMake
        run: cmake -B build -DCMAKE_GENERATOR="Visual Studio 16 2019" -A x64

      # Build the DLL using CMake
      - name: Build DLL
        run: cmake --build build --config Release --target MyCppProject

      # Upload the DLL as an artifact
      - name: Upload DLL artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-dll
          path: build/Release/MyCppProject.dll


